### ISSUE TITLE
Adding a different starting page

### ISSUE THREAD

**Issue by coskoutelis** [whchien/funda-scraper#12]
Hey for the purpose of webscraping to make it more robust how about adding a starting page functionality as well? Basically not start from page 0 for a specific city but page 5 for example. 

The implementation would be pretty simple and I think I can already open a PR if you're OK with that

**Comment by whchien** [comment]
Hi @coskoutelis 

Thanks for the feedback. I added the argument for FundaScraper in the latest version (v1.0.8). Now you can pass page_start=5 for example to start at the different page.

**Comment by coskoutelis** [comment]
Hey Will, the page_start functionality is not working properly. For Example, I tried passing page_start=5 in FundaScraper and it is still the same number of pages (for example in Amsterdam 50 and also freezes when I am in page 46/50) I think it indicates to me something is faulty with the implementation in scrape.py in line 115 ` for i in tqdm(range(self.page_start, self.page_start + self.n_pages)):
`
