### ISSUE TITLE
neighbourhood name = na

### ISSUE THREAD

**Issue by NelisV** [whchien/funda-scraper#15]
in all cases so far seen, the neighbourhood name in the raw data result is NA. however the neighbourhood name can be found in the 'zip code' field.
![image](https://github.com/whchien/funda-scraper/assets/42404718/bac9f582-7414-4e27-a708-38c428e19887)

**Comment by whchien** [comment]
Hi @NelisV 

I've updated your feedback in the latest release (v1.0.9). Please let me know if something does not work. Thanks!

**Comment by NelisV** [comment]
@whchien It seems that now the listed since field always returns an NA. might this change have introduced that bug?
