### ISSUE TITLE
Range of prices

### ISSUE THREAD

**Issue by coskoutelis** [whchien/funda-scraper#16]
How about adding a range for prices, since right now it tends to upload a lot of parking spots as well which is not always desirable. Also being able to return the  max number of pages each city has would be a useful addition

**Comment by whchien** [comment]
Hi @coskoutelis  

I've updated your feedback in the latest release (v1.0.9). You can now specify min_price and max_price when you instantiate a FundaScraper object. Please let me know if anything does not work. Thanks!
