### ISSUE TITLE
scraping not progressing

### ISSUE THREAD

**Issue by PJVoorwinden** [whchien/funda-scraper#2]
I am running this funda scraper in Python Idle and after running it, the script freezes after starting the second phase.

![image](https://user-images.githubusercontent.com/83770653/213741506-9c265557-b4d4-4c4a-90f8-932210d3d6d9.png)

Is this because Funda uses anti-scraping scripts on their website? Or because of something else? Does it still work for you?

Greetings,

Jonathan

**Comment by whchien** [comment]
Hi Jonathan, 

What is the query you were using? I tested it with some samples, and it worked fine.

**Comment by vollit** [comment]
Got the same issue. I think it is indeed caused by the anti-scraping scripts from Funda.

**Comment by whchien** [comment]
Hi Volit, 

What error did you get exactly? I tried with both 3.9 and 3.10, and they seem to be working fine without errors in both .py and notebook environments.

**Comment by lisageurten** [comment]
Hi there,

I have got almost the same issue. In my first run I retrieve 15 results for an area (only the first funda page). Second run gives me 0 zero results. If I wait some time, I again obtain 15 results and then again the following runs give 0 results again.

I am curious if it still works for you or if you know what might be causing this behavior?

Greetings,

Lisa

**Comment by whchien** [comment]
Hi @PJVoorwinden @lisageurten 

I just updated the new version of funda_scraper. If you can install the latest version (v1.0.0), the scraping should work without problems now. Please let me know if you encounter anything unusual. All the feedback would be appreciated!
