### ISSUE TITLE
listed since date N/A

### ISSUE THREAD

**Issue by NelisV** [whchien/funda-scraper#22]
It seems that the listed since field always returns an NA. Could the latest neighbourhood name change have introduced this bug?

_Originally posted by @NelisV in https://github.com/whchien/funda-scraper/issues/15#issuecomment-1713869831_

**Comment by whchien** [comment]
Hi @NelisV  this is because Funda updated their interface in 2023. The listed_since information is only visible after users  @loggoin in. Therefore the current set up will only return NA.
