### ISSUE TITLE
Changing keep_cols in preprocessing

### ISSUE THREAD

**Issue by utkuarslan5** [whchien/funda-scraper#29]
It sounds like adding the flexibility to alter which columns to keep (in my case, I want the date_list) could be useful.
E.g. can update config.yaml before running scraper.
If you guide me how to, happy to implement!

**Comment by whchien** [comment]
Hi @utkuarslan5, in the latest release (v1.1.1), you can pass keep_extra_cols in preprocess_data function to keep more columns as you wish. Let me know if it does not work. Also feel free to open a pull request as well!
