### ISSUE TITLE
URL construction faulty for sold houses

### ISSUE THREAD

**Issue by EWoutersen** [whchien/funda-scraper#39]
Super helpful tool! 

There seems to be an issue with the URL construction for sold (or rented out) properties though. The URL built by the build_main_query_url-function misses a %5B and a %5D, which means that no properties are returned.

For Amsterdam the correct URL would be:

https://www.funda.nl/en/zoeken/koop?selected_area=%5B%22amsterdam%22%5D&availability=%5B%22unavailable%22%5D

But the tool uses: 

https://www.funda.nl/en/zoeken/koop?selected_area=%5B%22amsterdam%22%5D&availability=%22unavailable%22

**Comment by whchien** [comment]
Hi @EWoutersen this issue has been fixed in the latest release (v1.2.0). Please let me know if you encounter the same issue.
