### ISSUE TITLE
Scraper not retrieving any data

### ISSUE THREAD

**Issue by BTuyn** [whchien/funda-scraper#6]
![image](https://github.com/whchien/funda-scraper/assets/32613178/b98f885a-d7d3-4871-9695-faa712c722b2)

**Comment by light-bit** [comment]
I noticed this as well. Unfortunately Funda changed the layout of their website, it seems that the scraper has to be updated in order to work with this new layout.

Good news is that the bs4 still returns the page content. Let's hope someone has the time to update the scripts accordingly.

**Comment by PieterK123** [comment]
Same here. Would indeed be great if we can still get the script working.

**Comment by PieterK123** [comment]
You managed to get it working @BTuyn?

**Comment by dadadima94** [comment]
Same here!

**Comment by whchien** [comment]
Hi @BTuyn @light-bit @PieterK123 @dadadima94

I just updated the new version of funda_scraper. If you can install the latest version (v1.0.0), the scraping should work without problems now. Please let me know if you encounter anything unusual. All the feedback would be appreciated!

**Comment by BTuyn** [comment]
Sorry for the late response. Seems like the problem is fixed indeed, but after checking the update, I did notice some other bugs.
The raw dataframe seems fine, however, the clean dataframe is missing quite a lot of rows and isn't processing data properly for a few columns such as 'has_balcony' and 'has_garden'. This is a different issue than the previous issue though and I see somebody else already raised a issue ticket for it.

**Comment by whchien** [comment]
Hi @BTuyn 

Yes, you are correct. I removed the columns 'has_balcony' and 'has_garden' from the clean data frame. Funda changes how they describe these exteriors, so the original preprocessing script needs to be revised. I will include the new preprocessing logic in the next release.
